micronaut:
  server:
     port: 8081
  application:
    name: feedbackPub

endpoints:
  health:
    enabled: true
    sensitive: false
    url:
      enabled: true

nats:
  addresses: ${nats_host:localhost}
  username: ${nats_username:guest}
  password: ${nats_password:guest}
